language: c
sudo: false
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - libssl-dev
    - libyajl-dev
    - libyajl2

script:
  - dpkg-query -L libyajl-dev 
  - git clone https://github.com/jorisvink/kore
  - cd kore
  - sed -i '1s/^/JSONRPC=1\nNOTLS=1\nTASKS=1\n/' Makefile
  - make && make install
  - cd ..
  - kore -v
