language: c
sudo: false
dist: trusty
os:
  - linux

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - libssl-dev
    - libyajl-dev

script:
  - git clone https://github.com/jorisvink/kore
  - cd kore
  - sed -i '1s/^/JSONRPC=1\nNOTLS=1\nTASKS=1\n/' Makefile
  - make
  - cd ..
  - kore/kore -v
  - kore/kore flavor test
  - kore/kore build
